include ../shared.mk

SOURCES:=$(wildcard *.c)
CFLAGS+=-Werror

CFLAGS:= -I. -I${PROJECT_ROOT}/external/facil/ -I${PROJECT_ROOT}/external/facil/http/ -I${PROJECT_ROOT}/external/facil/fiobj/


include ../end.mk

